import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { randomUUID } from 'node:crypto';
import { mkdirSync } from 'node:fs';
import { resolve } from 'node:path';
import { maintain } from './maintenance.mjs';
const id = randomUUID().replaceAll('-', '');
const prefix = 'infohub-smoke-' + id;
const image = prefix + ':test';
const network = prefix + '-net';
const pg = prefix + '-pg';
const app = prefix + '-app';
const restored = prefix + '-restored';
const password = 'Fixture-' + randomUUID();
const databasePassword = randomUUID();
function docker(args, required = true) {
  const result = spawnSync('docker', args, {
    encoding: 'utf8',
    windowsHide: true,
    env: { ...process.env, POSTGRES_PASSWORD: databasePassword, PGPASSWORD: databasePassword },
    maxBuffer: 4 * 1024 * 1024,
  });
  if (required && (result.error || result.status !== 0))
    throw new Error(result.error?.message || result.stderr || 'Docker failed.');
  return result.stdout?.trim() || '';
}
async function ready(base) {
  const until = Date.now() + 90000;
  while (Date.now() < until) {
    try {
      return await maintain({ command: 'status', base });
    } catch {
      await new Promise((resolve) => setTimeout(resolve, 500));
    }
  }
  throw new Error('Container did not become ready.');
}
async function call(base, path, token, body) {
  const response = await fetch(base + '/api' + path, {
    method: body ? 'POST' : 'GET',
    headers: { ...(token ? { Authorization: 'Bearer ' + token } : {}), 'Content-Type': 'application/json' },
    body: body ? JSON.stringify(body) : undefined,
  });
  assert.ok(response.ok, `${path}: HTTP ${response.status}`);
  return response.json();
}
function start(name, database) {
  docker([
    'run',
    '-d',
    '--name',
    name,
    '--network',
    network,
    '--mount',
    'type=volume,destination=/data/files',
    '-e',
    'PGHOST=' + pg,
    '-e',
    'PGUSER=infohub',
    '-e',
    'PGPASSWORD',
    '-e',
    'PGDATABASE=' + database,
    '-p',
    '127.0.0.1::3210',
    image,
  ]);
  const address = docker(['port', name, '3210/tcp']);
  assert.match(address, /^127\.0\.0\.1:\d+$/);
  return 'http://' + address;
}
try {
  docker(['version']);
  docker(['build', '-t', image, '.']);
  docker(['network', 'create', network]);
  docker([
    'run',
    '-d',
    '--name',
    pg,
    '--network',
    network,
    '-e',
    'POSTGRES_PASSWORD',
    '-e',
    'POSTGRES_USER=infohub',
    '-e',
    'POSTGRES_DB=infohub',
    'postgres:17-alpine',
  ]);
  const until = Date.now() + 60000;
  while (!docker(['exec', pg, 'pg_isready', '-U', 'infohub'], false).includes('accepting connections')) {
    if (Date.now() > until) throw new Error('Container PostgreSQL did not start.');
    await new Promise((resolve) => setTimeout(resolve, 500));
  }
  const base = start(app, 'infohub');
  const health = await ready(base);
  const token = (await call(base, '/auth/setup', '', { password })).token;
  const asset = await call(base, '/items', token, {
    kind: 'knowledge',
    title: 'Docker验收',
    data: { content: '容器重启与恢复记录' },
  });
  assert.equal(docker(['exec', app, 'id', '-u']), '10001');
  docker(['restart', app]);
  await ready(base);
  const relogin = (await call(base, '/auth/login', '', { password })).token;
  assert.equal((await call(base, '/items/' + asset.id, relogin)).title, asset.title);
  const folder = resolve('.local/docker-tests', id);
  mkdirSync(folder, { recursive: true });
  const backup = await maintain({
    command: 'backup',
    base,
    file: resolve(folder, 'docker.infohub'),
    password,
  });
  docker(['exec', pg, 'psql', '-U', 'infohub', '-d', 'postgres', '-c', 'CREATE DATABASE restored']);
  const recoveryBase = start(restored, 'restored');
  await ready(recoveryBase);
  await maintain({
    command: 'restore',
    base: recoveryBase,
    file: backup.file,
    backupPassword: password,
    confirm: '恢复并替换',
  });
  const recoveredToken = (await call(recoveryBase, '/auth/login', '', { password })).token;
  assert.equal(
    (await call(recoveryBase, '/items/' + asset.id, recoveredToken)).data.content,
    '容器重启与恢复记录',
  );
  console.log(
    `Docker ${health.version} smoke passed: non-root startup, restart persistence, encrypted backup and clean-container restore.`,
  );
} finally {
  // All removable names are generated by this script; no existing deployment is selected.
  for (const name of [app, restored, pg]) {
    assert.ok(name.startsWith(prefix));
    docker(['rm', '-f', '-v', name], false);
  }
  docker(['network', 'rm', network], false);
  docker(['image', 'rm', image], false);
}
